/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-05-18 04:00:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ShoppingList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>買い物リスト</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body onLoad = \"document.F.submit():\">\r\n");
      out.write("    <h1>買い物リスト</h1>\r\n");
      out.write("    <form method = \"POST\" action = \"ShoppingListServlet\">\r\n");
      out.write("      <div style = \"position : absolute ; left : 10px;\">商品名</div>\r\n");
      out.write("      <div style = \"position : absolute ; left : 190px;\">個数</div>\r\n");
      out.write("      <div style = \"position : absolute ; left : 265px;\">メモ</div>\r\n");
      out.write("      <BR>\r\n");
      out.write("      <input type = \"text\" name = \"txtGoods\" required  maxlength = \"30\" style= \"position : absolute ; left : 10px;\"/>\r\n");
      out.write("      <input type = \"number\" name = \"txtNumber\"  min = \"0\" max = \"999\" style = \"position : absolute ; left : 190px ;\"/>\r\n");
      out.write("      <input type = \"text\" name = \"txtMemo\" maxlength = \"200\" style= \"position : absolute ; left : 265px ;\"/><BR><BR>\r\n");
      out.write("      <input type = \"submit\" value = \"登録\" name = \"btnRegister\"><br><br>\r\n");
      out.write("      <h2>未購入商品一覧</h2>\r\n");
      out.write("    </form>\r\n");
      out.write("    <form method = \"POST\" action= \"ShoppingListServlet\">\r\n");
      out.write("      <table border = \"1\" width = \"800\" >\r\n");
      out.write("        <tr>\r\n");
      out.write("          <th></th>\r\n");
      out.write("          <th>商品名</th>\r\n");
      out.write("          <th>個数</th>\r\n");
      out.write("          <th>メモ</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");
 Object size = request.getAttribute("size");
        String s;
        if(size != null){
          s = size.toString();
          int j = Integer.parseInt(s);
          for(int i = 0 ;i < j ; i++){ 
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("          <th><input type = \"radio\" value = \"");
      out.print(request.getAttribute("UUID"+i));
      out.write("\" name = \"rdoselect\"></th>\r\n");
      out.write("          <th><input type = \"text\" value = \"");
      out.print(request.getAttribute("name"+i));
      out.write("\" name = \"lblGoods");
      out.print(request.getAttribute("UUID"+i));
      out.write("\" required></th>\r\n");
      out.write("          <th><input type = \"number\" value = \"");
      out.print(request.getAttribute("num"+i));
      out.write("\" name = \"lblNumber");
      out.print(request.getAttribute("UUID"+i));
      out.write("\" required min = \"0\" max = \"999\"></th>\r\n");
      out.write("          <th><input type = \"text\" value = \"");
      out.print(request.getAttribute("memo"+i));
      out.write("\" name = \"lblMemo");
      out.print(request.getAttribute("UUID"+i));
      out.write("\"></th>\r\n");
      out.write("\r\n");
      out.write("          <th><button type = \"submit\" value = \"");
      out.print(request.getAttribute("UUID"+i));
      out.write("\" name = \"btnPurchase\">購入済</button></th>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("      </table>\r\n");
      out.write("      <button type = \"submit\" value = \"\" name = \"btnUpdate\">修正</button>\r\n");
      out.write("      <input type = \"submit\" value = \"削除\"name = \"btnDelete\">\r\n");
      out.write("    </form>\r\n");
      out.write("    ");
}else{
      out.write("\r\n");
      out.write("    <form method=\"GET\" action=\"ShoppingListServlet\" name =\"F\" >\r\n");
      out.write("      <meta http-equiv=\"refresh\" content=\"0;URL=http://localhost:8080/shoppinglistservlet/ShoppingListServlet\">\r\n");
      out.write("    </form>\r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
